[servers]
Maxbridge_Devlopment_Server ansible_host=89.116.32.43 ansible_user=root ansible_port=1807
dhellavita.in ansible_host=46.28.44.148 ansible_user=root
citysync.co.in ansible_host=187.127.135.132 ansible_user=root
