apiVersion: 1

datasources:
  - name: alertmanager-stack
    uid: alertmanager-stack
    type: alertmanager
    access: proxy
    url: http://alertmanager:9093
    orgId: 1
    isDefault: false
    editable: false
    jsonData:
      implementation: prometheus
      handleGrafanaManagedAlerts: false
