apiVersion: 1

deleteDatasources:
  - name: prometheus-1
    orgId: 1

datasources:
  - name: prometheus-1
    uid: prometheus-1
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    orgId: 1
    isDefault: true
    editable: false
    version: 1

    jsonData:
      httpMethod: POST
      manageAlerts: false
